spring:
  application:
    name: geography
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: secret

  # jpa:
  #   hibernate:
  #     ddl-auto: update  # Automatically updates the schema on startup
  sql:
    init:
      mode: always  # Ensures data.sql runs even with Hibernate ddl-auto

server:
  port: 8091

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    initial-instance-info-replication-interval-seconds: 40
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true